# Set Color and mouse
set -g default-terminal "xterm-256color"
set -g mouse on

# Set Prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# kill-session
bind-key X confirm-before -p "kill-sessions? (y/n) " 'kill-session'
# Move window left (prefix + Left Arrow)
bind-key Left swap-window -t -1 \; select-window -t -1
# Move window right (prefix + Right Arrow)
bind-key Right swap-window -t +1 \; select-window -t +1

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'janoamaral/tokyo-night-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-cowboy'
set -g @plugin 'laktak/tome'
set -g @tome_key '['
set -g @tome_editor nvim

run '~/.tmux/plugins/tpm/tpm'