alias ls='eza --icons --group-directories-first'
alias ll='eza -l --icons --group-directories-first'
alias la='eza -la --icons --group-directories-first'
alias lt='eza --tree --level=2'

alias cat='bat'
alias diff='delta'
alias grep='grep --color=auto'

alias sz='source ~/.zshrc'
alias agy='antigravity'

alias showalias='type'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ~='cd ~'

alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias gco='git checkout'
alias gb='git branch'
alias gd='git diff'
alias gf='git fetch'
alias gm='git merge'
alias gr='git rebase'

alias d='docker'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias dex='docker exec -it'
alias dlogs='docker logs -f'
alias dclean='docker system prune -af'

alias dc='docker-compose'
alias dcup='docker-compose up -d'
alias dcdown='docker-compose down'
alias dclogs='docker-compose logs -f'
alias dcrestart='docker-compose restart'

alias k='kubectl'
alias kgp='kubectl get pods'
alias kgd='kubectl get deployments'
alias kgs='kubectl get services'
alias kga='kubectl get all'
alias kaf='kubectl apply -f'
alias kdf='kubectl delete -f'
alias kdesc='kubectl describe'
alias klogs='kubectl logs -f'
alias kexec='kubectl exec -it'

alias tf='terraform'
alias tfa='terraform apply'
alias tfd='terraform destroy'
alias tfi='terraform init'
alias tfp='terraform plan'
alias tfv='terraform validate'

alias ssh-term='TERM=xterm-256color ssh'

alias wt='wezterm'
alias wts='wezterm start'
alias wtssh='wezterm ssh'
alias wtimg='wezterm imgcat'
alias wtk='wezterm show-keys'
