export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

source $ZSH/oh-my-zsh.sh

source "$HOME/.dotfiles/zsh/env.zsh"
source "$HOME/.dotfiles/zsh/plugins-loaded.zsh"
source "$HOME/.dotfiles/zsh/completion.zsh"
source "$HOME/.dotfiles/zsh/options.zsh"
source "$HOME/.dotfiles/zsh/keybindings.zsh"
source "$HOME/.dotfiles/zsh/function.zsh"

source ~/.zsh_aliases 2>/dev/null
source ~/.zsh_env 2>/dev/null
source ~/.zsh_local 2>/dev/null
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"